### ISSUE TITLE
Portential memory leak

### ISSUE THREAD

**Issue by insomnyawolf** [WhiteRedWolf/Circles#1]
static void Main()
        {

            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new playfield());
            while (true)
            {
                playfield.HPDrain();
            }
        }

The program cant be closed without task manager, this keeps running after you exit the form

**Comment by WhiteRedWolf** [comment]
I am not Supporting this Game anymore.
